- src/pages/Home.tsx
> #33 style : 달력 헤더 부분 스타일 수정

- src/pages/CompletedTodo.tsx
완성된 도전과제 페이지 스타일 수정
<br/>
<br/>
<br/>
> #41 style : 완성된 도전과제 페이지 스타일 수정

- src/api/axios.ts
- src/components/User/UserProfile.tsx
- src/components/common/Header.tsx
- src/hooks/useCompletedTodo.ts
- src/mock/browser.ts
- src/pages/CompletedTodo.tsx
- src/pages/CreateTodo/Achievements.tsx
- src/pages/Home.tsx
> #56  refactor : 배포 빌드 전 에러 수정

- src/mock/browser.ts
> #56  refactor : 배포 빌드 전 msw수정

- src/api/axios.ts
- src/pages/Home.tsx
> #60  refactor : baseUrl 변경

- src/api/axios.ts
- src/pages/Home.tsx
> #62  refactor : baseUrl 변경2

- src/components/Achievements/AchievementsList.tsx
- src/components/Games/GameList.tsx
- src/components/common/Loading.tsx
- src/hooks/useAchievements.ts
- src/hooks/useGames.ts
- src/pages/CreateTodo/Achievements.tsx
- src/pages/CreateTodo/Games.tsx
- 게임, 도전과제 예외처리 추가
- 로딩 컴포넌트 추가
- 도전과제리스트 애니메이션 추가
- Todo 생성 시 홈화면 이동, 예외 처리 추가
<br/>
https://github.com/PHJ-a/steam-todolist-frontend/assets/102671646/2a1541bd-bed5-4a32-9155-6fa4a85e2438
12.39.58.mov…
<br/>
<br/>
> 예외 처리 작업 및 로딩 추가

- src/api/axios.ts
- src/pages/Home.tsx
> #65  refactor : baseUrl 변경3

- src/pages/CreateTodo/Achievements.tsx
도전과제 페이지 alert => 스낵바 변경
<br/>
<br/>
브랜치 받으셔서 테스트 한번 해보고 잘되면 머지 부탁드립니다
<br/>
> Feature/67  도전과제 페이지 alert => 스낵바 변경

- src/pages/CreateTodo/Achievements.tsx
페이지 이동으로 스낵바 안뜨는 문제 해결
<br/>
<br/>
<br/>
> #71 refactor : 페이지 이동으로 스낵바 안뜨는 문제 해결

- src/api/axios.ts
baseurl https로 수정
<br/>
<br/>
<br/>
> fix : baseurl https로 수정

- vercel.json
> #75 error : 버셀 리프레쉬 할때마다 404에러 해결

- src/components/modal/TodoModal.tsx
- src/hooks/useCompletedTodo.ts
- src/hooks/useTodos.tsx
- src/pages/CompletedTodo.tsx
- src/pages/Home.tsx
- vercel.json
도전과제 페칭 동기화 안되는 문제 해결 
<br/>
<br/>
<br/>
> Feature/78 도전과제 페칭 동기화 안되는 문제 해결 

- src/style/global.ts
> #54 Style: 스크롤 추가

- src/components/List/List.tsx
- src/components/List/ListItem.tsx
- src/pages/Home.tsx
> #81 refactor : 도전과제 삭제후 낙관적 업데이트 안되는 문제

- src/components/Achievements/AchievementItem.tsx
- src/components/Achievements/AchievementsList.tsx
- src/components/Games/GameItem.tsx
- src/components/Games/GameList.tsx
- src/hooks/useAchievements.ts
- src/hooks/useGames.ts
- src/pages/CreateTodo/Achievements.tsx
- src/pages/CreateTodo/Games.tsx
- src/utils/format.ts
- 총 플레이시간, 최근플레이 데이터추가
- 유저가 todo3개일 경우 스낵바 보여주기
- 도전과제 item 디자인 변경
<br/>
<br/>
<br/>
> todo 생성 단계 페이지들 리팩토링

- src/components/List/ListItem.tsx
- src/components/modal/TodoModal.tsx
- src/hooks/useCompletedTodo.ts
- src/pages/CompletedTodo.tsx
- src/utils/days.ts
> #86 refactor : 부족한 부분 수정

- src/components/List/ListItem.tsx
- src/components/modal/TodoModal.tsx
- src/pages/CreateTodo/Achievements.tsx
- src/utils/days.ts
한국시간, 경과시간 리팩토링
<br/>
<br/>
<br/>
> Refactor/88 한국시간, 경과시간 리팩토링

- src/components/Games/GameItem.tsx
- src/components/List/ListItem.tsx
- src/components/common/Header.tsx
- src/components/snackBar/SnackBar.tsx
- src/pages/CreateTodo/Achievements.tsx
- 도전과제에서 버튼 클릭시 버튼 쪽으로 포커싱
- 에러, 도전과제가 없을 경우 예외처리
- 헤더에 margin변경
- 최근 플레이 null일 경우 플레이 없음 표시
- 도전과제 페이지에서 게임 이미지크기 줄임
- 스타일 컴포넌트 에러 해결
- #92 
<br/>
> [Chore]/#92 예외처리, 스타일 변경

- package-lock.json
- package.json
- src/App.tsx
- src/api/fetchs.ts
- src/hooks/useCompletedTodo.ts
- src/hooks/useTodos.tsx
- src/pages/Home.tsx
프로젝트 리액트 쿼리 도입
<br/>
<br/>
<br/>
> #94 feat : 프로젝트 리액트쿼리 도입

- src/components/Achievements/AchievementItem.tsx
- src/hooks/useAchievements.ts
- src/pages/CreateTodo/Achievements.tsx
- src/utils/format.ts
> [Chore] unlockTime 추가

- src/hooks/useCompletedTodo.ts
> #100 feat : 완성된 투두 페칭 주석처리

- src/components/Games/GameItem.tsx
- src/hooks/useGames.ts
- src/utils/format.ts
스팀 API에서 해당 유저의 키가 아니면, 최근플레이 시간 가져 올 수 없어서 삭제
> Chore : 최근플레이 시간 삭제

- src/api/fetchs.ts
- src/components/List/List.tsx
- src/components/List/ListItem.tsx
- src/hooks/useTodos.tsx
- src/pages/Home.tsx
> #104  feat : 완료된 도전과제 체크 버튼 추가

- src/pages/Home.tsx
> #108  feat : 도전과제 완료버튼 에러 스낵바 처리

- package-lock.json
- package.json
- src/App.tsx
- src/api/achievements.ts
- src/api/fetchs.ts
- src/api/games.ts
- src/hooks/useAchievements.ts
- src/hooks/useGames.ts
- src/hooks/useTodos.tsx
- src/pages/CreateTodo/Achievements.tsx
게임 불러오기, 도전과제 불러오기 리액트 쿼리로 추가
react-query-devtools 추가
- closes #106 
<br/>
> [feat] 리액트 쿼리 추가

- src/components/modal/infoModal.tsx
> #112  style : info모달 스타일 수정

- src/components/modal/infoModal.tsx
> #114  style : info모달 스타일 수정2

- src/hooks/useTodos.tsx
- src/pages/Home.tsx
> Feature/117 완료버튼 에러 throw 안되는 문제 해결

- src/api/fetchs.ts
- src/hooks/useCompletedTodo.ts
- src/hooks/useTodos.tsx
- src/pages/CompletedTodo.tsx
- src/pages/Home.tsx
> Refactor/completed todo  완료된 도전과제 더미 삭제, 실제 데이터 이용

- src/components/modal/TodoModal.tsx
- src/context/AuthContext.tsx
- src/pages/CompletedTodo.tsx
> Refactor/122 모달 더미데이터로 나오는 문제 해결

- src/context/AuthContext.tsx
> #116  QA : 스팀 페이지에서 로그인하지 않고 뒤로가기 시 로그인 하러 가기가 뜨지 않는 문제 해결

- src/context/AuthContext.tsx
> #124  refactor : 로그인 안하고 뒤로 가기시 모달 안뜨는 문제

- src/pages/Home.tsx
> #127  refactor : 로그인 안하고 뒤로가기 문제

- src/pages/Home.tsx
> #127  refactor : 로그아웃시 모달 안뜨는 문제

- src/components/common/PopOver.tsx
> #131  refactor : 팝오버 컴포넌트 리팩토링

- src/hooks/useTodos.tsx
- src/pages/Home.tsx
> Todo 완료 낙관적 업데이트로 변경 취소
